AllCops:
  AllowSymlinksInCacheRootDirectory: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'bundle/**/*'
    - 'vendor/**/*'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle:
  - key
  - table

Layout/LineLength:
  Max: 180 # we're not in the 80s anymore.

Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Max: 90
  Exclude:
  - spec/**/*_spec.rb

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Naming/FileName:
  Exclude:
  - Policyfile.rb # this is chef names

# This requires to add a comment inside nearly all file which could be
# considered as toil without value
Style/FrozenStringLiteralComment:
  Enabled: false

# I just like this explicit format :)
Style/RedundantConstantBase:
  Enabled: false

### Comma after each line in a list
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
